### ISSUE TITLE
Addition of Mistakes/Shabbiness

### ISSUE THREAD

**Issue by nimishbongale** [smaranjitghose/doc2pen#13]
Great work!

I'm not really sure how it is to be done, but it would be great if some mistakes and some amount of untidiness could be added on to the font as well! I don't think I need to explain why! 😄 

Cheers!

**Comment by smaranjitghose** [comment]
For the shabiness feel we can tinker with the background. However, I wouldn't suggest having strikethrough texts since many people using this would want to have their assignments/reports written which ideally should be error free. Although we can work for an additional whatsapp like strikethrough feature

**Comment by nimishbongale** [comment]
Yes, True

The point is that It looks a bit too neat without mistakes, almost suspiciously neat
