### ISSUE TITLE
Design a menu bar for the Editor which can be accessed in mobile devices too. The current one just acts like a navbar

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#300]
![mobile_view](https://user-images.githubusercontent.com/46641503/103168938-8c6c5380-485d-11eb-8606-b13cd66acb85.jpg)

**Comment by satyampandeygit** [comment]
Is this needs to be implemented using bootstrap?

**Comment by smaranjitghose** [comment]
> Is this needs to be implemented using bootstrap?

Not necessary but up to your convinience

**Comment by satyampandeygit** [comment]
Okay I will try this one

**Comment by ashuvssut** [comment]
Hello, please hear out my idea.
I will make a menubar that has a total width of the full screen. It will be a rectangular shaped container. in that container there will be buttons for each of the sliders. all the sliders that exists now will be hidden under the menubar. when user taps upon the button, its respective slider comes sliding in, thus, allowing the user to use the slider.

I think this is the best approach because i dont have to modify/edit the current html `form` elements. I will have to implement a menubar and just do a little css. 

will submit PR within 4days, kindly please assign me this issue.

**Comment by patel-atul** [comment]
I can di that please assign me this issue.
I will make the menu bar accesible for smaller screens

**Comment by smaranjitghose** [comment]
> Hello, please hear out my idea.
> I will make a menubar that has a total width of the full screen. It will be a rectangular shaped container. in that container there will be buttons for each of the sliders. all the sliders that exists now will be hidden under the menubar. when user taps upon the button, its respective slider comes sliding in, thus, allowing the user to use the slider.
> 
> I think this is the best approach because i dont have to modify/edit the current html `form` elements. I will have to implement a menubar and just do a little css.
> 
> will submit PR within 1 day, kindly please assign me this issue.

Please wait for the issue to be assigned and then proceed with a pr from next time so that everyone gets an equal opportunity

**Comment by ashuvssut** [comment]
@smaranjitghose, I am sorry for that. I will keep that in mind for the next time.

Can you please review my PR. Please suggest changes (if any).

**Comment by smaranjitghose** [comment]
> @smaranjitghose, I am sorry for that. I will keep that in mind for the next time.

No worries. We learn by doing. But keep in mind, open source is also about collaboration beyond the competition. 😊
