### ISSUE TITLE
In desktop, I can see no dropdown menu for download. Even on clicking the download menu, it just refreshes the page.

### ISSUE THREAD

**Issue by nishihere19** [smaranjitghose/doc2pen#335]

**Comment by ashuvssut** [comment]
please add a screenshot to help contributors fix it.

**Comment by nishihere19** [comment]
![image2](https://user-images.githubusercontent.com/63252119/103502464-4758aa80-4e77-11eb-8a59-5e6f9c8faa50.jpeg)
![image1](https://user-images.githubusercontent.com/63252119/103502467-49226e00-4e77-11eb-8dc2-e7232073fe54.jpeg)

**Comment by ashuvssut** [comment]
![image](https://user-images.githubusercontent.com/60546840/103502927-a8489a00-4e07-11eb-88c8-6e2450550529.png)

Actually this an alignment problem.

I have already submitted my PR #333 to solve this. It has been approved. This bug will be fixed after they merge my PR.

This issue is actually the same as #333. So You can close this issue.

**Comment by nishihere19** [comment]
Oh okk.
