### ISSUE TITLE
Remove inherited undesired stylings by using css modules

### ISSUE THREAD

**Issue by ashuvssut** [smaranjitghose/doc2pen#466]
Please have a look on this [issue](https://github.com/HITK-TECH-Community/Community-Website/issues/344).

I have observed the same in thing in doc2pen codebase.

there are css files that need to be converted to module.css. currently some css styles are globally defined and therefore can affect other stylings. we must use css modules to prevent that.

please assign me this issue

**Comment by anushbhatia** [comment]
And clean up the unnecessary files too.

**Comment by smaranjitghose** [comment]
@ashuvssut any updates brother?

**Comment by ashuvssut** [comment]
giving in 5mins

**Comment by smaranjitghose** [comment]
@ashuvssut @sanjay270899 @Abhijay007 .

Since Awesome Developer Portfolio is a part of the same open-source programs as Doc2Pen and we are planning to shift it to React (Eventually to Next) you are welcome to work on the transition issue for it and on parallel (not always but things like SEO, pre-loader, dark mode, etc) PRs for both projects if you wish

**Comment by ashuvssut** [comment]
sir, if you are talking about https://github.com/smaranjitghose/awesome-portfolio-websites, then I am very excited for it! Looking forward for those new issues.😁😁

**Comment by ashuvssut** [comment]
when is the new `branch` for react version getting pushed?

**Comment by smaranjitghose** [comment]
> Sir, when is the new `branch` for react version getting pushed?

Well, the transition would be:

- working on a branch `react`
- the base HTML,css one would be on master
- Once the react branch is stable, we will shift to master
