### ISSUE TITLE
Scroll Bar in Sketch Page✨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#871]
### Requirements
1. Scrollbar not present in sketch page due to which many options cannot be seen and can't be used.
2.  Also keep in mind functionality shouldn't be modified.
![image](https://user-images.githubusercontent.com/40017559/114614906-b9385f80-9cc2-11eb-97d3-30e5195cae25.png)

**Comment by subhasmitapradhan** [comment]
I want to give this a try. As well as the footer issue.

**Comment by anushbhatia** [comment]
Assigned for 1 day

**Comment by subhasmitapradhan** [comment]
I think it will be better to rather adjust the tool box a bit so that everything is available to user in one frame. One wont even need to scroll down every time he needs to use the other options.

**Comment by subhasmitapradhan** [comment]
I think it will be better to adjust the tool box so that it all comes in one frame for the user. 
It looks unprofessional every time one has to scroll down to use the rest tools.
Rather than adding the scrollbar I want to change the issue to make the toolbar fit the canvas size.
I think this change will be worth it.
