### ISSUE TITLE
Footer in sketch section.

### ISSUE THREAD

**Issue by Shivangi-ch** [smaranjitghose/doc2pen#931]
I would like to add the same footer which is there in other sections of website to the sketch section too.

Please assign this to me.

**Comment by ashuvssut** [comment]
we are thinking to implement a canvas which can expand limitlessly. canvas will expand when user scrolls up/down/right/left

Thus if there is footer under the sketchpage, when the user scrolls down the user will see the footer instead of an expanding canvas in downward direction

if we really need a footer section we can shift footer contents in the new sidebar which will come through #923 
we can design those contents using MUI components

**Comment by Furquan712** [comment]
I would like to work on this , Will you assignee me .please
